<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.course.cases.AddUserTest" tests="1" time="5.922" ignored="0" failures="1" timestamp="18 Feb 2019 01:31:11 GMT" skipped="0" hostname="DESKTOP-1J0QRU3" errors="0">
  <testcase name="addUser" time="5.922" classname="com.course.cases.AddUserTest">
    <failure type="java.lang.AssertionError" message="expected [{&quot;timestamp&quot;:1550453441315,&quot;status&quot;:500,&quot;error&quot;:&quot;Internal Server Error&quot;,&quot;exception&quot;:&quot;org.springframework.dao.DataIntegrityViolationException&quot;,&quot;message&quot;:&quot;\r\n### Error updating database.  Cause: java.sql.SQLException: Field &#039;id&#039; doesn&#039;t have a default value\r\n### The error may involve com.course.addUser-Inline\r\n### The error occurred while setting parameters\r\n### SQL: insert into         user(userName,password,sex,age,permission,isDelete)         values         (?,?,?,?,?,?);\r\n### Cause: java.sql.SQLException: Field &#039;id&#039; doesn&#039;t have a default value\n; SQL []; Field &#039;id&#039; doesn&#039;t have a default value; nested exception is java.sql.SQLException: Field &#039;id&#039; doesn&#039;t have a default value&quot;,&quot;path&quot;:&quot;/v1/addUser&quot;}] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [{"timestamp":1550453441315,"status":500,"error":"Internal Server Error","exception":"org.springframework.dao.DataIntegrityViolationException","message":"\r\n### Error updating database.  Cause: java.sql.SQLException: Field 'id' doesn't have a default value\r\n### The error may involve com.course.addUser-Inline\r\n### The error occurred while setting parameters\r\n### SQL: insert into         user(userName,password,sex,age,permission,isDelete)         values         (?,?,?,?,?,?);\r\n### Cause: java.sql.SQLException: Field 'id' doesn't have a default value\n; SQL []; Field 'id' doesn't have a default value; nested exception is java.sql.SQLException: Field 'id' doesn't have a default value","path":"/v1/addUser"}] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.course.cases.AddUserTest.addUser(AddUserTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- addUser -->
</testsuite> <!-- com.course.cases.AddUserTest -->
